clang \
    -L/usr/local/lib \
    -lm \
    -lGL \
    -lGLEW \
    -lSDL2 \
    -lavutil \
    -I/usr/local/include \
    -I/usr/local/include/GL \
    -I/usr/local/include/SDL2 \
    -I/usr/local/include \
    -Isrc \
    -Isrc/ui \
    -Isrc/mtlib \
    -Isrc/views \
    -Isrc/modules \
    -Isrc/modules/gl \
    -Isrc/modules/ui \
    -Isrc/modules/wm \
    -Isrc/modules/text \
    src/modules/gl/gl_connector.c \
    src/modules/gl/gl_floatbuffer.c \
    src/modules/ui/ui_manager.c \
    src/modules/ui/view.c \
    src/modules/ui/eh_drag.c \
    src/modules/ui/tg_text.c \
    src/modules/ui/tg_color.c \
    src/modules/ui_connector.c \
    src/modules/ui_compositor.c \
    src/modules/wm/wm_event.c \
    src/modules/wm/wm_connector.c \
    src/modules/text/font.c \
    src/modules/text/text.c \
    src/mtlib/mtbitmap.c \
    src/mtlib/mttexmap.c \
    src/mtlib/mtchannel.c \
    src/mtlib/mtmap.c \
    src/mtlib/mtmath2.c \
    src/mtlib/mtmath3.c \
    src/mtlib/mtmath4.c \
    src/mtlib/mtmemory.c \
    src/mtlib/mtvector.c \
    src/mtlib/mtstring.c \
    src/mtlib/mtcstring.c \
    src/eh_songs.c \
    src/player.c \
    src/zenmusic.c \
    src/common.c \
    -o bin/zenmusic
